services:
  haproxy:
    image: docker.io/library/haproxy:3.0.11 # previously 3.3-dev
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - tts1
      - api1
      - blips
      - radio
      - radio-gibberish
      - tts-dashboard
    ports:
      - 5002:5002
      - 8888:8888
  api1:
    build: .
    command: python -u tts-api.py
    networks:
      - default
    volumes:
      - ./cache:/workspace/cache:rw
    environment:
      # only enable this if you're having gpu errors you need to debug.
      #- TORCH_USE_CUDA_DSA=1
      - TORCH_CUDNN_SDPA_ENABLED=1
      - TORCH_LOG=perf_hints
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  tts1:
    build: .
    command: python -u tg_tts_service.py
    networks:
      - default
    volumes:
      - ./speaker_latents:/workspace/speaker_latents:rw
      - ./voice_mapping.json:/workspace/voice_mapping.json:rw
      - ./huggingfacecache:/root/.cache/huggingface:rw
      - ${PWD}/db:/workspace/db
    environment:
      - TORCH_USE_CUDA_DSA=1
      - TORCH_CUDNN_SDPA_ENABLED=1
      - TORCH_LOG=perf_hints
      - DB_PATH=/workspace/db/tts_stats.db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  tts-dashboard:
    build: .
    command: python -u tts_dashboard.py
    networks:
      - default
    volumes:
      - ${PWD}/db:/workspace/db
    environment:
      - DB_PATH=/workspace/db/tts_stats.db
    ports:
      - 5007:5007
  blips:
    build: .
    command: python -u tg_tts_service_blips_new.py
    networks:
      - default
    volumes:
      - ./speaker_latents:/workspace/speaker_latents:rw
      - ./voice_mapping.json:/workspace/voice_mapping.json:rw
      - ./sfx_mapping.json:/workspace/sfx_mapping.json:rw
    environment:
      - TORCH_USE_CUDA_DSA=1
      - TORCH_CUDNN_SDPA_ENABLED=1
      - TORCH_LOG=perf_hints
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  radio:
    build: .
    command: python -u tg_tts_service_radio.py
    networks:
      - default
    volumes:
      - ./cache:/workspace/cache:rw
  radio-gibberish:
    build: .
    command: python -u tg_tts_service_radio_gibberish.py
    networks:
      - default
    volumes:
      - ./cache:/workspace/cache:rw
    environment:
      # only enable this if you're having gpu errors you need to debug.
      #- TORCH_USE_CUDA_DSA=1
      - TORCH_CUDNN_SDPA_ENABLED=1
      - TORCH_LOG=perf_hints
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
